### ISSUE TITLE
Migrate to Helix 3

### ISSUE THREAD

**Issue by rofe** [adobe/fedpub#107]
These are likely the relevant steps to migrate this project to Helix 3:

**Preparation (`main` branch)**
- [x] Merge branch `master` into `main`
- [x] Add Helix Bot to repo
- [x] Add `hlx3` flag to Sidekick config so it uses Helix Admin API
- [x] Remove ESI includes from code (except `head.html`)
- [x] Remove `sourceHash` in `helix-query.yaml`
- [x] Move `sitemap-*.xml` to Sharepoint (leave `sitemap.xml`)
- [x] Regenerate `sitemap-*.xml` with new canonicals (no `.html`)
- [x] Front-load `preview` and `live` from index

**Switch to Helix 3**
- [x] redirect `.html` extensions to no extension in `redirects.xlsx`
- [ ] Remove onedrive-listener (@dominique-pfister)
- [ ] Remove `sourceHash` column in index
- [ ] Remove `.html` extension in `path` column, using the following expression in a new column:
```
=LEFT(C2, IF(ISNUMBER(FIND(".html", C2)),FIND(".html", C2) - 1, LEN(C2)))
```
(provided the `path` column is column C). Then copy the values without `.html` in the new column, and paste **values** into the `path` column
- [ ] Republish index
- [ ] Change origin to `main--fedpub--adobe.hlx3.page` in Fastly
- [ ] Delete `master` branch

@kptdobe @tripodsan please chime in in case I forgot or misrepresented something.

**Comment by narcis-radu** [comment]
hey @rofe - #108 seems to be covering the 3rd item on the checklist [1]. Is there anything else needed?
[1] - https://github.com/adobe/fedpub/pull/108/files#diff-6a80ee76ad4e48d165e03f9ae91c7a4753795ea77faef27da241294076f4031dR18

**Comment by mokimo** [comment]
@rofe @kptdobe @tripodsan what would be the next steps for the move to helix 3, is there anything we (the eurovision team) can still help with? I also crosschecked the migration list from [theblog](https://github.com/adobe/theblog/issues/687#issuecomment-908919481)

Most of the initial preparation checklist is done. 2 open points:
- remove `.html` endings from sitemaps
We plan to publish the regenerated sitemaps after the switch to helix 3, so we don't break anything. 
- Front-load preview and live from index
I'd gladly help, can anyone give me some pointers on what needs to be done? My initial guess are some adaptions in the sidekick config

**Comment by rofe** [comment]
> * Front-load preview and live from index
>   I'd gladly help, can anyone give me some pointers on what needs to be done? My initial guess are some adaptions in the sidekick config

No, bulk publishing isn't something we see in the sidekick (definitely in the organizer at one point). For now I would create a small node script that fetches and walks the query index JSON and posts the paths to the respective [Helix Admin API](https://opensource.adobe.com/helix-home/admin/index.html) action. Similar to how you currently generate the sitemap.

**Comment by mokimo** [comment]
> No, bulk publishing isn't something we see in the sidekick (definitely in the organizer at one point). For now I would create a small node script that fetches and walks the query index JSON and posts the paths to the respective [Helix Admin API](https://opensource.adobe.com/helix-home/admin/index.html) action. Similar to how you currently generate the sitemap.

That's done ✅  

Encountered errors for 6 articles where the query-index seems to be wrong. Those articles also lead to 404s without helix 3.
```js
const data = [{
  path: '/kr/documentcloud/sign/hub/document-types/binding-vs-non-binding-contract.html',
},
{    
  path: '/kr/documentcloud/sign/hub/document-types/bill-of-sale-vs-title.html',
},
{    
  path: '/kr/documentcloud/sign/hub/document-types/as-is-real-estate-contract.html',
},
{   
  path: '/kr/creativecloud/video/hub/features/basic-video-editing.html',
},
{    
  path: '/kr/creativecloud/video/hub/features/best-app-to-edit-videos.html',
},
{    
  path: '/kr/creativecloud/video/hub/features/does-mp4-provide-lossless-compression.html',
}]
```

**Comment by kptdobe** [comment]
This morning, I chatted with the EMEA localisation team and discovered they work like this:
- they copied the full folder hierarchy under `/_drafts`
- they create, edit, author, review the docx pages in here
- to "publish" a page, they d&d it from `/_drafts` to its correct place under `/`

While this will still work, the move to `hlx3` would allow them to avoid duplicating everything under `/_drafts` and work directly "in the right place" (production folder). The difference would be made by the `Publish` button which would be the only way to make the page publicly available (before was not the case, someone knowing the url could see the page).

As part of the migration, is there any plan to train the authors with this new capability ? This would allow to simplify a lot the authoring / publication process ?

**Comment by mokimo** [comment]
Done !
