### ISSUE TITLE
Use context path for static file delivery through adobe.com CDN

### ISSUE THREAD

**Issue by rofe** [adobe/fedpub#12]
In order to simplify the Akamai origin config and to avoid polluting the adobe.com URL space, we decided to use a `/hub` root folder for static resources.

**Comment by rofe** [comment]
#13 will take care of static GH resources. For anything under `/hlx_*`, we will need to rewrite URLs to `/hub/hlx_*` and back in the outer CDN. @trieloff could you help with that?

cc @davidnuescheler

**Comment by trieloff** [comment]
@rofe `/hub/hlx_*` on the outer CDN to `/hlx_*` on the inner CDN is easy.

What do you mean with the reverse?

**Comment by rofe** [comment]
Helix is putting out HTML with `/hlx_*` URLs, and I guess we'll need to rewrite those to `/hub/hlx_*` too.

**Comment by trieloff** [comment]
That's not something the CDN can do for us, we need to adjust the pipeline for that or change it on the client-side.

**Comment by rofe** [comment]
Will be handled in https://github.com/adobe/helix-home/issues/183
