### ISSUE TITLE
Integrate FEDS library

### ISSUE THREAD

**Issue by narcis-radu** [adobe/fedpub#14]
Add FEDS library to the fedPub project

**Comment by rofe** [comment]
Note that this change has dropped the lighthouse score by more than 10 points...

**Comment by narcis-radu** [comment]
Hi @rofe, a small degradation is expected since additional scripts are being loaded. I think this huge downgrade is related to the CORS issues - FEDS library cannot render the experience. A ticket has been created yesterday and we're waiting for WebPS to make the changes.
cc @overmyheadandbody
