### ISSUE TITLE
Add default 'robots' meta tag

### ISSUE THREAD

**Issue by overmyheadandbody** [adobe/fedpub#45]
The SEO team is requesting that there is a default `<meta name="robots" content="follow, index">` added to the `head` section. If a page requires a different value, then it can be added in the 'Metadata' section of the article.

**Comment by rofe** [comment]
@overmyheadandbody @narcis-radu Note that the outer CDN is still sending a `http.X-Robots-Tag: noindex, nofollow` header which will probably override whatever robots meta tag is defined. This is part of the default Helix outer CDN setup, and its removal should be added to any go-live checklist.
