### ISSUE TITLE
Localization Requirements for FedPub

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/fedpub#76]
### Requirements

- Need to support all the region-lang combination in the publish folder supported by a.com surfaces.
- Authors must be able to share regions-lang translated content (example - French content in France can be same as French content in Canada)
- Authors must be able to create and manage their own regional content
- Authors must be able to preview & publishing of content in regions
- Authors must be able to auto publish into correct region-lang folders upon return of content from localization workflow
- Authors must be able to manage regional metadata like Title, Description, SEO Targets
- Authors must be able to tag article text as do not translate 
- Authors must be able to define localization languages per single articles 
- Authors should not have to move individual files to localization folders, an automated task is preferred to improve usability.
  ( Example - if we select 90 Sign articles for loc across the /guides, the /doc-type, and the /features folders, we need to keep track of which articles belong to which subfolder )

@rofe @davidnuescheler

**Comment by mokimo** [comment]
This doesn't seem to be worked on - or parts of that already work.
For this reason I'll close this, feel free to reopen if this is not resolved yet.
