### ISSUE TITLE
Page is blank, no content served from Helix

### ISSUE THREAD

**Issue by narcis-radu** [adobe/fedpub#77]
### Expected Behaviour
HTML page should have content in `<body>`
https://www.adobe.com/documentcloud/acrobat/hub/how-to/how-to-combine-pdfs-chromebook.html

### Actual Behaviour
`<body>` does not have any content
https://www.adobe.com/documentcloud/acrobat/hub/how-to/how-to-combine-pdfs-chromebook.html

### Reproduce Scenario (including but not limited to)
Go to https://www.adobe.com/documentcloud/acrobat/hub/how-to/how-to-combine-pdfs-chromebook.html and check page source.

cc @rofe, @kptdobe

**Comment by avanishgandhi** [comment]
We are still similar issues yet? We see similar issues on other pages too.
https://www.adobe.com/documentcloud/sign/hub/document-types/how-to-create-invoice-for-cleaning-services.html 

@rofe

**Comment by rofe** [comment]
@avanishgandhi if you encounter this issue, the workaround is to just re-publish the pahe from hlx.page and wait 5 minutes for the akamai cache to expire.

**Comment by mokimo** [comment]
Seems like a known issue to @rofe / the helix team and not fedpub specific. All the linked demo pages are working now.

For this reason I'll close this issue
