### ISSUE TITLE
Remove legacy sidekick config

### ISSUE THREAD

**Issue by rofe** [adobe/fedpub#90]
Once #89 is implemented and all authors' sidekick bookmarklets are updated, the old config under `/tools/sidekick/plugins.js` can be removed. We could verify no more requests have been made to `/tools/sidekick/plugins.js` made during the last 7 days before doing so.

**Comment by mokimo** [comment]
Seems to be fixed here https://github.com/adobe/fedpub/pull/93
So I'll close this issue
